# App
spring.application.name=ordino
spring.profiles.active=${APP_PROFILE}

# Server
server.port=8080

# Database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JWT
security.jwt.secret-key=40873b70f9f92ca1d739ef364cdb2b2c38e9be04fc2680e4fc45b458a75285d7
security.jwt.expiration-time=3600000 #1h in millisecond

# Flyway
spring.flyway.url=jdbc:mysql://${DB_URL}/${DB_NAME}
spring.flyway.user=root
spring.flyway.password=${MYSQL_ROOT_PASSWORD}
spring.flyway.placeholders.appUser=${DB_USER}
spring.flyway.placeholders.appPassword=${DB_PASSWORD}
spring.flyway.placeholders.dbName=${DB_NAME}
spring.flyway.placeholders.adminUsername=${ADMIN_USERNAME}
spring.flyway.placeholders.adminPassword=${ADMIN_PASSWORD}
spring.flyway.placeholders.adminEmail=${ADMIN_EMAIL}
spring.flyway.placeholders.adminPhoneNumber=${ADMIN_PHONE_NUMBER}

