# App
spring.application.name=ordino
spring.profiles.active=${APP_PROFILE:local}

# Server
server.port=9000

# Database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JWT
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000
security.refresh-token.expiration-time=604800000

# Flyway
spring.flyway.url=jdbc:mysql://${DB_URL}/${DB_NAME}
spring.flyway.user=root
spring.flyway.password=${MYSQL_ROOT_PASSWORD}
spring.flyway.placeholders.appUser=${DB_USER}
spring.flyway.placeholders.appPassword=${DB_PASSWORD}
spring.flyway.placeholders.dbName=${DB_NAME}
spring.flyway.placeholders.adminUsername=${ADMIN_USERNAME}
spring.flyway.placeholders.adminPassword=${ADMIN_PASSWORD}
spring.flyway.placeholders.adminEmail=${ADMIN_EMAIL}
spring.flyway.placeholders.adminPhoneNumber=${ADMIN_PHONE_NUMBER}

#Frontend
frontend.url=http://localhost:8080

